In [5]:
import pandas as pd
import os

In [6]:
# Verify if the code is run as an script or in an interactive environment
# Get the current directory

if '__file__' in globals():
    current_dir = os.path.dirname(__file__)
else:
    current_dir = os.getcwd()

current_dir

'/home/tux/cursos/curso-pandas'

In [7]:
csv_path = os.path.join(current_dir, "datasets", "bestsellers.csv")
csv_path

'/home/tux/cursos/curso-pandas/datasets/bestsellers.csv'

In [8]:
df_books = pd.read_csv(csv_path, sep=',', header=0, names=['Names', 'Author', 'User Rating',	'Reviews',	'Price', 'Year', 'Genre'])
df_books

,Names,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [9]:
json_path = os.path.join(current_dir, "datasets", "hpcharacters.json")
json_path

'/home/tux/cursos/curso-pandas/datasets/hpcharacters.json'

In [10]:
pd.read_json(json_path)

,Name,Link,Descr,Gender,Species/Race,Blood,School,Profession
0,Mrs. Abbott,https://www.hp-lexicon.org/character/abbott-fa...,"Mrs. Abbott was the mother of Hannah Abbott, a...",Female,Witch,Muggle-born,Unknown,Unknown
1,Hannah Abbott,https://www.hp-lexicon.org/character/abbott-fa...,Hannah Abbott is a Hufflepuff student in Harry...,Female,Witch,Half-blood,Hogwarts - Hufflepuff,Landlady of the Leaky Cauldron
2,Abel Treetops,https://www.hp-lexicon.org/character/abel-tree...,Abel Treetops was a wizard from Cincinnati who...,Male,Wizard,Unknown,Unknown,Unknown
3,Euan Abercrombie,https://www.hp-lexicon.org/character/abercromb...,Euan Abercrombie was a small boy with prominen...,Male,Wizard,Unknown,Hogwarts - Gryffindor,Unknown
4,Aberforth Dumbledore,https://www.hp-lexicon.org/character/dumbledor...,"Aberforth Dumbledore was a tall, thin, grumpy-...",Male,Wizard,Half-blood,Hogwarts - Student,Barman
...,...,...,...,...,...,...,...,...
1935,Georgi Zdravko,https://www.hp-lexicon.org/character/georgi-zd...,Georgi Zdravko played KeeperÂ for the Bulgarian...,Male,Wizard,Unknown,Unknown,Quidditch player (Seeker)
1936,Zograf,https://www.hp-lexicon.org/character/zograf/,Zograf played KeeperÂ for theÂ Bulgarian Nationa...,NaN,Wizard,Unknown,Unknown,Quidditch player (Keeper)
1937,Zonko,https://www.hp-lexicon.org/character/zonko/,Founder(?) of Zonkoâ€™s Joke Shop. Possibly a re...,NaN,Unknown,Unknown,Unknown,Unknown
1938,Valentina VÃ¡zquez,https://www.hp-lexicon.org/character/valentina...,Valentina VÃ¡zquez was President of the Argenti...,Female,Witch,Unknown,Unknown,President of the Argentinian Council of Magic
1939,Zygmunt Budge,https://www.hp-lexicon.org/character/zygmunt-b...,Zygmunt Budge is considered to be one of the m...,Male,Wizard,Unknown,Hogwarts - Student,"Potions Master, Potioneer, Inventor, Author"

In [11]:
# The typ parameter specifies the type of object that should be returned by the read_json function
pd.read_json(json_path, typ='series')

0       {'Name': 'Mrs. Abbott', 'Link': 'https://www.h...
1       {'Name': 'Hannah Abbott', 'Link': 'https://www...
2       {'Name': 'Abel Treetops', 'Link': 'https://www...
3       {'Name': 'Euan Abercrombie', 'Link': 'https://...
4       {'Name': 'Aberforth Dumbledore', 'Link': 'http...
                              ...
1935    {'Name': 'Georgi Zdravko', 'Link': 'https://ww...
1936    {'Name': 'Zograf', 'Link': 'https://www.hp-lex...
1937    {'Name': 'Zonko', 'Link': 'https://www.hp-lexi...
1938    {'Name': 'Valentina VÃ¡zquez', 'Link': 'https:/...
1939    {'Name': 'Zygmunt Budge', 'Link': 'https://www...
Length: 1940, dtype: object

# Cargar otros Datasets:

In [15]:
pokemon_path = os.path.join(current_dir, "datasets", "Pokemon_full.csv")
diabetes_path = os.path.join(current_dir, "datasets", "Diabetes-Dataset.csv")
games_path = os.path.join(current_dir, "datasets", "games.csv")

In [16]:
df_pokemon = pd.read_csv(pokemon_path)
df_pokemon

,name,pokedex id,height,weight,type,secundary type,hp,attack,defense,sp atk,sp def,speed
0,bulbasaur,1,7,69,grass,poison,45,49,49,65,65,45
1,ivysaur,2,10,130,grass,poison,60,62,63,80,80,60
2,venusaur,3,20,1000,grass,poison,80,82,83,100,100,80
3,charmander,4,6,85,fire,NaN,39,52,43,60,50,65
4,charmeleon,5,11,190,fire,NaN,58,64,58,80,65,80
...,...,...,...,...,...,...,...,...,...,...,...,...
885,drakloak,886,14,110,dragon,ghost,68,80,50,60,50,102
886,dragapult,887,30,500,dragon,ghost,88,120,75,100,75,142
887,zacian,888,28,1100,fairy,NaN,92,130,115,80,115,138
888,zamazenta,889,29,2100,fighting,NaN,92,130,115,80,115,138
889,eternatus,890,200,9500,poison,dragon,140,85,95,145,95,130

In [17]:
df_games = pd.read_csv(games_path)
df_games

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,1507,Back to the Future: The Game,"Dec 22, 2010",['Telltale Games'],3.2,94,94,"['Adventure', 'Point-and-Click']",Back to the Future: The Game is one of Telltal...,['Very enjoyable game. The story adds onto the...,763,5,223,67
1508,1508,Team Sonic Racing,"May 21, 2019","['Sumo Digital', 'Sega']",2.9,264,264,"['Arcade', 'Racing']",Team Sonic Racing combines the best elements o...,"['jogo morto mas bom', 'not my cup of tea', ""C...",1.5K,49,413,107
1509,1509,Dragon's Dogma,"May 22, 2012",['Capcom'],3.7,210,210,"['Brawler', 'RPG']","Set in a huge open world, Dragonâ€™s Dogma: Dark...","['Underrated.', 'A grandes rasgos, es como un ...",1.1K,45,487,206
1510,1510,Baldur's Gate 3,"Oct 06, 2020",['Larian Studios'],4.1,165,165,"['Adventure', 'RPG', 'Strategy', 'Tactical', '...","An ancient evil has returned to Baldur's Gate,...",['Bu tÃ¼re bu oyunla girmeye Ã§alÄ±ÅŸmak hataydÄ± s...,269,79,388,602
1511,1511,The LEGO Movie Videogame,"Feb 04, 2014","['WB Games', 'TT Fusion']",2.8,184,184,"['Adventure', 'Puzzle']",Join Emmet and an unlikely group of resistance...,"['Legal', 'Pretty Average Lego Game But It Was...",1.7K,11,239,73